DROP TABLE users;
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phoneNumber INT NOT NULL,
    password VARCHAR(50) NOT NULL
);